
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { SessionProvider } from 'next-auth/react'
import { auth } from '@/auth'
import './globals.css'
import NProgressWrapper from '@/components/ui/nprogress-bar'
import HomeLayoutNavigation from './_components/home-layout-navbar'
import { GlobalNavbar } from './(protected)/_components/global-navbar'
import Footer from '@/components/ui/footer'
import Header from './_components/home-layout-navbar2'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({

  children,
}: {
  children: React.ReactNode
}) {
  const session = await auth();
  return (
    <>
      <SessionProvider session={session}>
        <NProgressWrapper />
        <html lang="en">
          <body
            className="bg-slate-50" >
            {/* <HomeLayoutNavigation /> */}
            <Header />
            <div className='p-2 w-full '>
              {session ? <GlobalNavbar /> : null}
            </div>
            {children}
            <Footer />
          </body>
        </html>
      </SessionProvider >
    </>

  )
}
